services:
  caddy:
    build: https://github.com/Kevincible/docker-compose#main:caddy/caddy-build
    restart: unless-stopped
    networks:
      vlan:
        ipv4_address: $ADDR
    volumes:
      - $CONFDIR/Caddyfile:/etc/caddy/Caddyfile

networks:
  vlan:
    name: docker_vlan
    external: true
