services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    networks:
      - bridge
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=Asia/Shanghai
      - PLEX_CLAIM=$CLAIM
    volumes:
      - plex-data:/config
      - media:/data
    devices:
      - /dev/dri:/dev/dri

volumes:
  plex-data:
    external: true
  media:
    external: true