services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    networks:
      vlan:
        ipv4_address: $ADDR
    environment:
      - TZ=Asia/Shanghai
      - PLEX_CLAIM=$CLAIM
    volumes:
      - plex-data:/config
      - media:/data
    devices:
      - /dev/dri:/dev/dri

volumes:
  plex-data:
    external: true
  media:
    external: true

networks:
  vlan:
    name: docker_vlan
    external: true